[tools]
zig = "0.15.2"
zls = "0.15.1"

[tasks.main]
run = "zig run src/main.zig -- $@"
run_windows = "zig run src/main.zig --"

[tasks.unit]
run = "zig test src/main.zig"

[tasks.e2e]
run = [
    "zig test --test-filter e2e src/merge.e2e.zig",
    "zig test --test-filter e2e src/parse.e2e.zig",
]

[tasks.tests]
depends = ["unit", "e2e"]
